# Numpy
- create array
- maths
- operations

In [ ]:
x = [[1,2,3],
     [3,2,1]]
result = [a + b for a, b in zip(x[0], x[1])]
print(result)
# print(x)

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[3,4,5]])
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
(2, 3)


In [3]:
print(x.sum())

18


In [4]:
print(x.sum(axis=0)) # sum of each column


[4 6 8]


In [5]:
print(x.sum(axis=1)) # sum of each row

[ 6 12]


In [6]:
a = np.array([1,2,3])  # simple 1d matrix
b = np.array([[1,1],[2,2],[3,3]]) # 2d matrix
c = np.array([[[1,1],[2,2],[3,3]]])
print(a.shape, a.ndim)
print(b.shape, b.ndim)
print(c.shape, c.ndim)


(3,) 1
(3, 2) 2
(1, 3, 2) 3


In [7]:
print(b)

[[1 1]
 [2 2]
 [3 3]]


In [8]:
print(c)

[[[1 1]
  [2 2]
  [3 3]]]


# matrix creation
- sequential
    - arange
    - linspace
- random
    - rand
    - randint
    - uniform


In [10]:
x = np.arange(1, 11, .5) # start, end, step
x

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [11]:
y = np.linspace(1, 11, 15) # start, end, number of element
print(y)

[ 1.          1.71428571  2.42857143  3.14285714  3.85714286  4.57142857
  5.28571429  6.          6.71428571  7.42857143  8.14285714  8.85714286
  9.57142857 10.28571429 11.        ]


In [12]:
np.arange(1, 11, .5).reshape(4, 5) # reshape to 4x5 matrix

array([[ 1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5]])

In [16]:
np.arange(1, 11, 1).shape

(10,)

In [17]:
np.arange(1, 11, 1).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
x1 = np.array([[1,2,3],[4,5,6]])
x2 = np.array([[4,2,3],[2,6,6]])


In [21]:
print(x1 + x2)

[[ 5  4  6]
 [ 6 11 12]]


In [22]:
print(x1 - x2)

[[-3  0  0]
 [ 2 -1  0]]


In [23]:
print(x1 * x2)
print(x1 - x2)
print(x1 / x2)
print(x1 // x2)
print(x1 ** x2)
print(x1 % x2)
# comparison in numpy results in boolean array
print(x1 > x2)
print(x1 < x2)
print(x1 >= x2)
print(x1 <= x2)

[[ 4  4  9]
 [ 8 30 36]]
[[-3  0  0]
 [ 2 -1  0]]
[[0.25       1.         1.        ]
 [2.         0.83333333 1.        ]]
[[0 1 1]
 [2 0 1]]
[[    1     4    27]
 [   16 15625 46656]]
[[1 0 0]
 [0 5 0]]
[[False False False]
 [ True False False]]
[[ True False False]
 [False  True False]]
[[False  True  True]
 [ True False  True]]
[[ True  True  True]
 [False  True  True]]


In [26]:
a = np.random.rand()
a

0.039042197340882434

In [27]:
b = np.random.rand(3, 3)
b

array([[0.72662373, 0.12837573, 0.38841854],
       [0.8512212 , 0.36761447, 0.08677799],
       [0.75725794, 0.17861541, 0.95979238]])

In [28]:
np.set_printoptions(precision=2)

In [29]:
b

array([[0.73, 0.13, 0.39],
       [0.85, 0.37, 0.09],
       [0.76, 0.18, 0.96]])

In [39]:
b = np.random.randint(0, 10, (3, 3))
b.std()

2.0608041101101566

In [40]:
c = np.random.uniform(0, 10, (3, 3))
c.mean()

4.911563196295371